// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcppQMCIntegration
List rcppQMCIntegration(Function integrand, uint32_t N, int id, int s, int m, double probability);
RcppExport SEXP rmcqmcint_rcppQMCIntegration(SEXP integrandSEXP, SEXP NSEXP, SEXP idSEXP, SEXP sSEXP, SEXP mSEXP, SEXP probabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Function >::type integrand(integrandSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type id(idSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type probability(probabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(rcppQMCIntegration(integrand, N, id, s, m, probability));
    return rcpp_result_gen;
END_RCPP
}
// rcppMCIntegration
List rcppMCIntegration(Function integrand, uint32_t N, int s, int m, double probability);
RcppExport SEXP rmcqmcint_rcppMCIntegration(SEXP integrandSEXP, SEXP NSEXP, SEXP sSEXP, SEXP mSEXP, SEXP probabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Function >::type integrand(integrandSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type probability(probabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(rcppMCIntegration(integrand, N, s, m, probability));
    return rcpp_result_gen;
END_RCPP
}
