# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppQMCIntegration <- function(integrand, N, id, s, m, probability) {
    .Call('rmcqmcint_rcppQMCIntegration', PACKAGE = 'rmcqmcint', integrand, N, id, s, m, probability)
}

rcppQMCIntegrationSobol <- function(integrand, N, sobolMatrix, s, m, probability) {
    .Call('rmcqmcint_rcppQMCIntegrationSobol', PACKAGE = 'rmcqmcint', integrand, N, sobolMatrix, s, m, probability)
}

rcppMCIntegration <- function(integrand, N, s, m, probability) {
    .Call('rmcqmcint_rcppMCIntegration', PACKAGE = 'rmcqmcint', integrand, N, s, m, probability)
}

