# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppDigitalNetPoints <- function(df, id, dimR, dimF2, count, shiftVector) {
    .Call('rmcqmcint_rcppDigitalNetPoints', PACKAGE = 'rmcqmcint', df, id, dimR, dimF2, count, shiftVector)
}

rcppQMCIntegration <- function(integrand, N, df, id, s, m, probability) {
    .Call('rmcqmcint_rcppQMCIntegration', PACKAGE = 'rmcqmcint', integrand, N, df, id, s, m, probability)
}

rcppMCIntegration <- function(integrand, N, s, m, probability) {
    .Call('rmcqmcint_rcppMCIntegration', PACKAGE = 'rmcqmcint', integrand, N, s, m, probability)
}

